### ISSUE TITLE
Add ReSharper 2017.1 support

### ISSUE THREAD

**Issue by obechny** [Zvirja/ReSharperPlugin.XUnitTestRunnerSpeedBooster#1]
Hi,

could you please add support for the new ReSharper 2017.1.3?

Thank you!

**Comment by zvirja** [comment]
Thanks for your interest in this plugin :)
It appeared that JetBrains has already fixed that issue (tested with R# 2017.1.3), so you shouldn't suffer from it more. I've just updated the Readme file to indicate that.

If you still observe any issues - please report them to R# team.
